### ISSUE TITLE
train on mdr

### ISSUE THREAD

**Issue by ZhouQianang** [boomluo02/ADMFlow#2]
Thank you for your outstanding work. I have a question regarding the training on MDR. Why is only the `batch_1` sequence taken from the dataset (as seen on line 36 of MDR.py)? Furthermore, what does the different `batch_n` represent in the dataset? For example, what is the difference between `/dt1/train/batch_1` and `/dt1/train/batch_2`？

**Comment by boomluo02** [comment]
I apologize for the misunderstanding. Because our training sets are huge, we packaged them in batches to make uploading and downloading easier. Each batch has roughly the same number of samples, and during training, we place all of the samples in a folder called "dataset/MDR/dt1/train," which may be adjusted to the path of the dataset on your computer.

**Comment by ZhouQianang** [comment]
Thank you for your reply, it's really helpful to me.
